FROM opensuse/tumbleweed:latest

RUN zypper --non-interactive install clang clang-tools cmake ninja sudo && \
    zypper clean --all

WORKDIR /paclook
COPY CMakeLists.txt .
COPY src/ src/

RUN cmake -G Ninja -S . -B build -DCMAKE_CXX_COMPILER=clang++ && \
    cmake --build build

CMD ["/bin/bash"]
