FROM nixos/nix:latest

# Enable flakes
RUN mkdir -p /etc/nix && \
    echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

# Install build dependencies and bash using nix-env
RUN nix-env -iA nixpkgs.clang nixpkgs.cmake nixpkgs.ninja nixpkgs.bash

WORKDIR /paclook
COPY CMakeLists.txt .
COPY src/ src/

RUN cmake -G Ninja -S . -B build -DCMAKE_CXX_COMPILER=clang++ && \
    cmake --build build

CMD ["bash"]
