FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y clang clang-tools ninja-build sudo python3 python3-pip && \
    pip3 install --break-system-packages cmake && \
    apt-get clean

WORKDIR /paclook
COPY CMakeLists.txt .
COPY src/ src/

RUN cmake -G Ninja -S . -B build -DCMAKE_CXX_COMPILER=clang++ && \
    cmake --build build

CMD ["/bin/bash"]
