FROM alpine:latest

RUN apk update && apk add build-base clang samurai sudo python3 py3-pip && \
    pip3 install --break-system-packages cmake

WORKDIR /paclook
COPY CMakeLists.txt .
COPY src/ src/

RUN cmake -G Ninja -S . -B build -DCMAKE_CXX_COMPILER=clang++ && \
    cmake --build build

CMD ["/bin/sh"]
