FROM fedora:latest

RUN dnf install -y gcc-c++ cmake make sudo && \
    dnf clean all

WORKDIR /paclook
COPY CMakeLists.txt .
COPY src/ src/

RUN mkdir build && cd build && \
    cmake .. && \
    make -j$(nproc)

CMD ["/bin/bash"]
